/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as RideTrackRouteImport } from './routes/ride.track'
import { Route as RideOptionsRouteImport } from './routes/ride.options'
import { Route as DriverTripsRouteImport } from './routes/driver.trips'
import { Route as DriverTripRouteImport } from './routes/driver.trip'
import { Route as DriverEarningsRouteImport } from './routes/driver.earnings'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/driver/',
  path: '/driver/',
  getParentRoute: () => rootRouteImport,
} as any)
const RideTrackRoute = RideTrackRouteImport.update({
  id: '/ride/track',
  path: '/ride/track',
  getParentRoute: () => rootRouteImport,
} as any)
const RideOptionsRoute = RideOptionsRouteImport.update({
  id: '/ride/options',
  path: '/ride/options',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverTripsRoute = DriverTripsRouteImport.update({
  id: '/driver/trips',
  path: '/driver/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverTripRoute = DriverTripRouteImport.update({
  id: '/driver/trip',
  path: '/driver/trip',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverEarningsRoute = DriverEarningsRouteImport.update({
  id: '/driver/earnings',
  path: '/driver/earnings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/activity': typeof ActivityRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/trip': typeof DriverTripRoute
  '/driver/trips': typeof DriverTripsRoute
  '/ride/options': typeof RideOptionsRoute
  '/ride/track': typeof RideTrackRoute
  '/driver/': typeof DriverIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/activity': typeof ActivityRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/trip': typeof DriverTripRoute
  '/driver/trips': typeof DriverTripsRoute
  '/ride/options': typeof RideOptionsRoute
  '/ride/track': typeof RideTrackRoute
  '/driver': typeof DriverIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/activity': typeof ActivityRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/trip': typeof DriverTripRoute
  '/driver/trips': typeof DriverTripsRoute
  '/ride/options': typeof RideOptionsRoute
  '/ride/track': typeof RideTrackRoute
  '/driver/': typeof DriverIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/activity'
    | '/login'
    | '/search'
    | '/services'
    | '/settings'
    | '/signup'
    | '/welcome'
    | '/driver/earnings'
    | '/driver/trip'
    | '/driver/trips'
    | '/ride/options'
    | '/ride/track'
    | '/driver/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/activity'
    | '/login'
    | '/search'
    | '/services'
    | '/settings'
    | '/signup'
    | '/welcome'
    | '/driver/earnings'
    | '/driver/trip'
    | '/driver/trips'
    | '/ride/options'
    | '/ride/track'
    | '/driver'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/activity'
    | '/login'
    | '/search'
    | '/services'
    | '/settings'
    | '/signup'
    | '/welcome'
    | '/driver/earnings'
    | '/driver/trip'
    | '/driver/trips'
    | '/ride/options'
    | '/ride/track'
    | '/driver/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ActivityRoute: typeof ActivityRoute
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  WelcomeRoute: typeof WelcomeRoute
  DriverEarningsRoute: typeof DriverEarningsRoute
  DriverTripRoute: typeof DriverTripRoute
  DriverTripsRoute: typeof DriverTripsRoute
  RideOptionsRoute: typeof RideOptionsRoute
  RideTrackRoute: typeof RideTrackRoute
  DriverIndexRoute: typeof DriverIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/': {
      id: '/driver/'
      path: '/driver'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ride/track': {
      id: '/ride/track'
      path: '/ride/track'
      fullPath: '/ride/track'
      preLoaderRoute: typeof RideTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ride/options': {
      id: '/ride/options'
      path: '/ride/options'
      fullPath: '/ride/options'
      preLoaderRoute: typeof RideOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/trips': {
      id: '/driver/trips'
      path: '/driver/trips'
      fullPath: '/driver/trips'
      preLoaderRoute: typeof DriverTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/trip': {
      id: '/driver/trip'
      path: '/driver/trip'
      fullPath: '/driver/trip'
      preLoaderRoute: typeof DriverTripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/earnings': {
      id: '/driver/earnings'
      path: '/driver/earnings'
      fullPath: '/driver/earnings'
      preLoaderRoute: typeof DriverEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ActivityRoute: ActivityRoute,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  WelcomeRoute: WelcomeRoute,
  DriverEarningsRoute: DriverEarningsRoute,
  DriverTripRoute: DriverTripRoute,
  DriverTripsRoute: DriverTripsRoute,
  RideOptionsRoute: RideOptionsRoute,
  RideTrackRoute: RideTrackRoute,
  DriverIndexRoute: DriverIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
